/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eGLDNxyrn75
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Chat() {
  return (
    (<div className="flex flex-col h-screen">
      <div className="bg-background border-b border-muted p-4">
        <div className="flex items-center gap-4">
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>A</AvatarFallback>
          </Avatar>
          <div className="text-lg font-medium">Alice</div>
        </div>
      </div>
      <div className="flex-1 overflow-auto p-4 bg-background">
        <div className="space-y-4">
          <div className="flex items-start gap-4">
            <Avatar className="w-8 h-8">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>A</AvatarFallback>
            </Avatar>
            <div className="bg-card rounded-lg p-3 max-w-[75%]">
              <div className="font-medium text-card-foreground">Alice</div>
              <div className="text-sm text-muted-foreground">Hey there! How's it going?</div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="bg-primary rounded-lg p-3 max-w-[75%] text-primary-foreground">
              <div className="font-medium">You</div>
              <div className="text-sm">I'm doing great, thanks for asking! How about you?</div>
            </div>
            <Avatar className="w-8 h-8">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>Y</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-4">
            <Avatar className="w-8 h-8">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>B</AvatarFallback>
            </Avatar>
            <div className="bg-card rounded-lg p-3 max-w-[75%]">
              <div className="font-medium text-card-foreground">Bob</div>
              <div className="text-sm text-muted-foreground">
                I'm doing well too! Glad to hear you're having a good day.
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="bg-primary rounded-lg p-3 max-w-[75%] text-primary-foreground">
              <div className="font-medium">You</div>
              <div className="text-sm">That's great to hear! We should plan a get-together soon.</div>
            </div>
            <Avatar className="w-8 h-8">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>Y</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </div>
      <div className="bg-background border-t border-muted p-4">
        <div className="flex items-center gap-2">
          <Textarea
            placeholder="Type your message..."
            className="flex-1 resize-none rounded-lg p-2 border border-muted focus:border-primary focus:ring-0" />
          <Button>Send</Button>
        </div>
      </div>
    </div>)
  );
}
