/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NCKAgYVqnJu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function HANDS() {
  return (
    (<div className="w-full max-w-4xl mx-auto py-12 md:py-20">
      {/* <div className="space-y-4 text-center">
        <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Help and Support</h1>
        <p className="text-muted-foreground md:text-xl">
          Find answers to your questions and get the help you need. Browse our FAQ or contact our support team if you
          can&apos;t find what you're looking for.
        </p>
      </div>
      <div className="mt-12 space-y-6">
        <Collapsible className="rounded-lg border">
          <CollapsibleTrigger
            className="flex items-center justify-between gap-4 p-4 font-medium transition-colors hover:bg-muted">
            <span>How do I update my account information?</span>
            <ChevronDownIcon className="h-5 w-5 transition-transform data-[state=open]:rotate-180" />
          </CollapsibleTrigger>
          <CollapsibleContent className="border-t p-4 text-muted-foreground">
            To update your account information, follow these steps:
            <ol className="mt-2 list-decimal space-y-2 pl-4">
              <li>Log in to your account on our website.</li>
              <li>Click on the "Account" or "Profile" section.</li>
              <li>Update your personal information, such as your name, email address, or password.</li>
              <li>Save the changes and your updated information will be reflected in your account.</li>
            </ol>
            If you have any trouble updating your account, please don't hesitate to contact our support team.
          </CollapsibleContent>
        </Collapsible>
        <Collapsible className="rounded-lg border">
          <CollapsibleTrigger
            className="flex items-center justify-between gap-4 p-4 font-medium transition-colors hover:bg-muted">
            <span>How do I change my billing information?</span>
            <ChevronDownIcon className="h-5 w-5 transition-transform data-[state=open]:rotate-180" />
          </CollapsibleTrigger>
          <CollapsibleContent className="border-t p-4 text-muted-foreground">
            To update your billing information, follow these steps:
            <ol className="mt-2 list-decimal space-y-2 pl-4">
              <li>Log in to your account on our website.</li>
              <li>Navigate to the "Billing" or "Subscription" section.</li>
              <li>Click on the "Update Payment Method" or "Change Billing\n Information" option.</li>
              <li>Enter your new payment details, such as a different credit card or bank account.</li>
              <li>Review and confirm the changes, and your new billing information will be saved.</li>
            </ol>
            If you have any issues with updating your billing information, please contact our support team for
            assistance.
          </CollapsibleContent>
        </Collapsible>
        <Collapsible className="rounded-lg border">
          <CollapsibleTrigger
            className="flex items-center justify-between gap-4 p-4 font-medium transition-colors hover:bg-muted">
            <span>How do I access my product features?</span>
            <ChevronDownIcon className="h-5 w-5 transition-transform data-[state=open]:rotate-180" />
          </CollapsibleTrigger>
          <CollapsibleContent className="border-t p-4 text-muted-foreground">
            To access your product features, follow these steps:
            <ol className="mt-2 list-decimal space-y-2 pl-4">
              <li>Log in to your account on our website.</li>
              <li>Navigate to the "Products" or "Dashboard" section.</li>
              <li>Locate the product you want to access and click on the "Features" or "Manage" button.</li>
              <li>Explore the available features and settings for your product.</li>
              <li>If you have any questions or need help, don't hesitate to contact our support team.</li>
            </ol>
          </CollapsibleContent>
        </Collapsible>
        <Collapsible className="rounded-lg border">
          <CollapsibleTrigger
            className="flex items-center justify-between gap-4 p-4 font-medium transition-colors hover:bg-muted">
            <span>How do I troubleshoot an issue with the product?</span>
            <ChevronDownIcon className="h-5 w-5 transition-transform data-[state=open]:rotate-180" />
          </CollapsibleTrigger>
          <CollapsibleContent className="border-t p-4 text-muted-foreground">
            To troubleshoot an issue with the product, follow these steps:
            <ol className="mt-2 list-decimal space-y-2 pl-4">
              <li>
                Check our documentation or knowledge base for any troubleshooting guides or FAQs related to your issue.
              </li>
              <li>
                Ensure that you are using the latest version of the product and that your system meets the minimum
                requirements.
              </li>
              <li>Try restarting or refreshing the product to see if the issue resolves itself.</li>
              <li>
                If the issue persists, please contact our support team with a detailed description of the problem,
                including any error messages or steps you've taken to troubleshoot.
              </li>
              <li>
                Our support team will be happy to assist you and provide further guidance to help resolve the issue.
              </li>
            </ol>
          </CollapsibleContent>
        </Collapsible>
      </div>
      <div className="mt-12 space-y-4">
        <h2 className="text-2xl font-bold">Send us a query</h2>
        <form className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" placeholder="Enter your email" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="message">Message</Label>
            <Textarea id="message" placeholder="Enter your message" rows={4} />
          </div>
          <Button type="submit" className="w-full">
            Submit
          </Button>
        </form>
      </div> */}
    </div>)
  );
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}
