/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iOm6rNnIdmW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Item_form() {
  return (
    (<div className="max-w-2xl mx-auto p-6 sm:p-8 md:p-10">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl font-bold">Add New Rental</CardTitle>
          <CardDescription>Fill out the details to list your rental.</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="grid gap-6">
            <div className="grid gap-2">
              <Label htmlFor="name" className="text-sm font-medium">
                Rental Name
              </Label>
              <Input id="name" placeholder="Cozy Mountain Cabin" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="image" className="text-sm font-medium">
                Upload Image
              </Label>
              <Input id="image" type="file" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="rent" className="text-sm font-medium">
                Rent per Day
              </Label>
              <Input id="rent" type="number" placeholder="$150" />
            </div>
          </form>
        </CardContent>
        <CardFooter>
          <div className="flex justify-end">
            <Button>Upload</Button>
          </div>
        </CardFooter>
      </Card>
    </div>)
  );
}
