/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rwQSmABOr1R
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Lend_items() {
  return (
    (<div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-3xl font-bold mb-6">All Items</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div className="bg-white shadow-md rounded-lg overflow-hidden">
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Cozy Cabin</h2>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rent per day:</span>
              <span className="font-medium">$50</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Status:</span>
              <span className="text-green-500 font-medium">Available</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented by:</span>
              <span className="font-medium">John Doe</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented from:</span>
              <span className="font-medium">2023-05-01</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented till:</span>
              <span className="font-medium">2023-05-07</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Renter's mobile:</span>
              <span className="font-medium">123-456-7890</span>
            </div>
            <div className="mt-4">
              <Button className="w-full">Chat with Renter</Button>
            </div>
          </div>
        </div>
        <div className="bg-white shadow-md rounded-lg overflow-hidden">
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Beach Bungalow</h2>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rent per day:</span>
              <span className="font-medium">$75</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Status:</span>
              <span className="text-red-500 font-medium">Rented</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented by:</span>
              <span className="font-medium">Jane Smith</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented from:</span>
              <span className="font-medium">2023-06-01</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented till:</span>
              <span className="font-medium">2023-06-15</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Renter's mobile:</span>
              <span className="font-medium">987-654-3210</span>
            </div>
            <div className="mt-4">
              <Button className="w-full">Chat with Renter</Button>
            </div>
          </div>
        </div>
        <div className="bg-white shadow-md rounded-lg overflow-hidden">
          <div className="p-4">
            <h2 className="text-xl font-semibold mb-2">Mountain Retreat</h2>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rent per day:</span>
              <span className="font-medium">$100</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Status:</span>
              <span className="text-green-500 font-medium">Available</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented by:</span>
              <span className="font-medium">-</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented from:</span>
              <span className="font-medium">-</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Rented till:</span>
              <span className="font-medium">-</span>
            </div>
            <div className="flex items-center mb-2">
              <span className="text-gray-500 mr-2">Renter's mobile:</span>
              <span className="font-medium">-</span>
            </div>
            <div className="mt-4">
              <Button className="w-full">Chat with Renter</Button>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}
