/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UZ3QtqQ0ZlD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Rented_items() {
  const rentals = [
    {
      id: 1,
      item: "Camping Gear",
      rentedOn: "2023-06-01",
      dueOn: "2023-06-15",
      timeRemaining: "14 days",
      rentPerDay: "$10",
    },
    {
      id: 2,
      item: "Power Tools",
      rentedOn: "2023-05-15",
      dueOn: "2023-05-30",
      timeRemaining: "5 days",
      rentPerDay: "$15",
    },
    {
      id: 3,
      item: "Kayak",
      rentedOn: "2023-07-01",
      dueOn: "2023-07-15",
      timeRemaining: "20 days",
      rentPerDay: "$20",
    },
    {
      id: 4,
      item: "Lawn Mower",
      rentedOn: "2023-06-15",
      dueOn: "2023-06-30",
      timeRemaining: "10 days",
      rentPerDay: "$12",
    },
  ]
  return (
    (<div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-3xl font-bold mb-6">My Rentals</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {rentals.map((rental) => (
          <Card key={rental.id}>
            <CardHeader>
              <CardTitle>{rental.item}</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-muted-foreground">Rented On</p>
                  <p>{rental.rentedOn}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Due On</p>
                  <p>{rental.dueOn}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Time Remaining</p>
                  <p>{rental.timeRemaining}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Rent Per Day</p>
                  <p>{rental.rentPerDay}</p>
                </div>
              </div>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button size="sm">Chat with Owner</Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>)
  );
}
