# Generated by Django 5.0.6 on 2024-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swiftly", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
