# Generated by Django 5.0.6 on 2024-06-15 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
    ]
