# Generated by Django 5.0.6 on 2024-06-15 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_message_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="author",
        ),
    ]
