# Generated by Django 5.0.6 on 2024-06-15 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_chatmessage_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
